version: "3.7"
services:
  app:
    build:
      args:
        user: nanang
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: perpus
    container_name: perpus-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - perpus

  db:
    image: mysql:5.7
    container_name: perpus-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: perpust
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - "5001:3306"
    networks:
      - perpus

  nginx:
    image: nginx:alpine
    container_name: perpus-nginx
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - perpus

networks:
  perpus:
    driver: bridge
